### ISSUE TITLE
As a content creator I want to livestream directly from my webcam

### ISSUE THREAD

**Issue by pabloVoorvaart** [NFTsTv/nftstv#8] opened 2022-12-24 11:48 UTC
Required for alpha: 

- [ ] Rework control buttons and status feedback

**Comment by Mario-SO** [comment] 2023-01-29 13:06
maybe related to #24 ?

**Comment by Mario-SO** [comment] 2023-01-29 13:17
The title of the issue is actually done, you can stream from your webcam but still with some problems to solve. I think we can close this one and create other issues that give more detail over the problems that exist when streaming with the webcam.

**Closed by Mario-SO** 2023-01-29 13:17 UTC
Labels: story
